# MySQL Database Configuration
mysql:
  host: localhost
  port: 3306
  database: ezeconomy
  username: root
  password: password
  table: balances
  jdbc-params: "useSSL=false&serverTimezone=UTC&cachePrepStmts=true&prepStmtCacheSize=1024&prepStmtCacheSqlLimit=4096&useServerPrepStmts=true&elideSetAutoCommits=true&maintainTimeStats=false&useLocalSessionState=true&rewriteBatchedStatements=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&tcpKeepAlive=true&connectTimeout=8000&socketTimeout=30000"
  pool:
    enabled: true
    maximum-pool-size: 32
    minimum-idle: 8
    connection-timeout-ms: 8000
    idle-timeout-ms: 240000
    max-lifetime-ms: 1200000
