name: Feature tests

on:
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - 'ezeconomy-bungeecord/**'
      - 'ezeconomy-bungeecord-proxy/**'
      - 'ezeconomy-papi/**'
      - 'ezeconomy-bukkit/**'
      - 'ezeconomy-redis/**'
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'ezeconomy-bungeecord/**'
      - 'ezeconomy-bungeecord-proxy/**'
      - 'ezeconomy-papi/**'
      - 'ezeconomy-bukkit/**'
      - 'ezeconomy-redis/**'

jobs:
  feature-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - paper-version: "26.1.2.build.57-stable"
            mockbukkit-groupId: "org.mockbukkit.mockbukkit"
            mockbukkit-artifactId: "mockbukkit-v26.1.2"
            mockbukkit-version: "4.113.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'

      - name: Cache Maven local repository
        uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-v2-feature-${{ matrix.paper-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-v2-feature-${{ matrix.paper-version }}-

      - name: Run feature tests
        run: mvn -B -Dpaper.version=${{ matrix.paper-version }} -Dmockbukkit.groupId=${{ matrix.mockbukkit-groupId }} -Dmockbukkit.artifactId=${{ matrix.mockbukkit-artifactId }} -Dmockbukkit.version=${{ matrix.mockbukkit-version }} -Pfeature-tests -Dtest=*FeatureTest test


